name: AWS Request Sign

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Check code for high priority rules
      id: pmd
      uses: pmd/pmd-github-action@v1
      with:
        version: 'latest'
        sourcePath: 'src/classes'
        rulesets: 'rulesets/highPriorityRules.xml'
        analyzeModifiedFilesOnly: false

    - name: Fail build if there are violations
      if: steps.pmd.outputs.violations != 0
      run: exit 1

    - name: Check code for low priority rules
      uses: pmd/pmd-github-action@v1
      with:
        version: 'latest'
        sourcePath: 'src/classes'
        rulesets: 'rulesets/lowPriorityRules.xml'
        analyzeModifiedFilesOnly: false

    - name: Validate with ant
      run: ant validate -Dsf.username=${{secrets.SALESFORCE_USERNAME}} -Dsf.password=${{secrets.SALESFORCE_PASSWORD}}
